### ISSUE TITLE
Could you solve my questions belows? Thank you.

### ISSUE THREAD

**Issue by Kelly-ZH** [kenkyusha/eyeGazeToScreen#1]
Hello kenkyusha,
  I am a student working in the field of line of gaze estimation, your work that has realized Xucong Zhang‘s paper, and converts the angle of the CNN output to concrete 2D coordinates, has been a great help to me. I have a few questions, and I hope to receive your reply.
1. How do you get the 3D gaze vectors (relative to the camera coordinate system) to project onto a 2D screen, where does this mathematical derivation come from [here](https://github.com/kenkyusha/eyeGazeToScreen/blob/29db2bb18b6add190e518c91e8f9db79eea864a8/helper_fn.py#L56), can you give me any references about it?
2.  If you customize the input video(set the value of cust_vid), calc_metrics [here](https://github.com/kenkyusha/eyeGazeToScreen/blob/29db2bb18b6add190e518c91e8f9db79eea864a8/helper_fn.py#L24) will return an error, something like below. What's wrong with it, is it the version of Numpy I downloaded?
> Traceback (most recent call last):
  File "point_2_screen.py", line 502, in <module>
    main()
  File "point_2_screen.py", line 493, in main
    _, MAE, CEP, CE95 = calc_metrics((demo.true_pos, demo.cur_pos))
  File "C:\Users\Administrator.DESKTOP-TI37VJ6\Desktop\pytorch_mpiigaze-master\helper_fn.py", line 49, in calc_metrics
    ER = np.sqrt(np.sum(np.square(rng_pos-cur_pos), axis=1))
  File "<__array_function__ internals>", line 6, in sum
  File "E:\Anaconda\envs\mpiigaze\lib\site-packages\numpy\core\fromnumeric.py", line 2240, in sum
    initial=initial, where=where)
  File "E:\Anaconda\envs\mpiigaze\lib\site-packages\numpy\core\fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
3.  I do not  understand the meaning of this [code.](https://github.com/kenkyusha/eyeGazeToScreen/blob/29db2bb18b6add190e518c91e8f9db79eea864a8/point_2_screen.py#L474) Could you explain it to me?

Yours,
Hang Zhang

**Comment by kenkyusha** [comment]
Hello!
1. The equations are line equations in 2d maybe 3d domain
2. I tried right now the script with my own video and did not have any error, make sure you have .avi file 
3. This part computes metrics for the custom video and saves them
Hope this helps!

**Comment by Kelly-ZH** [comment]
> Hello!
> 
> 1. The equations are line equations in 2d maybe 3d domain
> 2. I tried right now the script with my own video and did not have any error, make sure you have .avi file
> 3. This part computes metrics for the custom video and saves them
>    Hope this helps!

Thank you for your reply, and about 1, I really have no idea why these linear equations can solve for the fixation point, can you give me more references or cues, thank you very much.

**Comment by Kelly-ZH** [comment]
> > Hello!
> > 
> > 1. The equations are line equations in 2d maybe 3d domain
> > 2. I tried right now the script with my own video and did not have any error, make sure you have .avi file
> > 3. This part computes metrics for the custom video and saves them
> >    Hope this helps!
> 
> Thank you for your reply, and about 1, I really have no idea why these linear equations can solve for the fixation point, can you give me more references or cues, thank you very much.

Hello, I already know the meaning of these linear equations, but I have another question, what does the [bottom_line](https://github.com/kenkyusha/eyeGazeToScreen/blob/b6472eb4b5515a76106e7a71628560f931e0b2a4/screen_conf.py#L12) mean? I really really looking forward to your answer，you will do me  a good favor.
